export const ACTIONTYPES = {
  CONTACT: {
    SEND_EMAIL_INIT: 'CONTACT/SEND_EMAIL_INIT',
    SEND_EMAIL_FULFILLED: 'CONTACT/SEND_EMAIL_FULFILLED',
    SEND_EMAIL_REJECTED: 'CONTACT/SEND_EMAIL_REJECTED',
  },
};
